[package]
name = "vec3-rs"
version = "0.1.3"
edition = "2021"
description = "A simple 3D vector math library"
repository = "https://github.com/DazorPlasma/vec3-rs"
authors = ["dazor"]
documentation = "https://docs.rs/vec3-rs"
readme = "README.md"
license = "MIT"
license-file = "LICENSE"
keywords = ["math", "vector", "vector3", "3d"]
categories = ["data-structures", "graphics", "mathematics"]

[profile.release]
lto = true

[dependencies]
rand = "0.8.5"
thiserror = "1.0.44"
